ALTER TABLE LVMAMA_PET.MARK_COUPON_RELATE_USER ADD COUPON_ID NUMBER(11);     
ALTER TABLE LVMAMA_PET.MARK_COUPON_RELATE_USER ADD CREATE_TIME DATE ;
COMMENT ON COLUMN LVMAMA_PET.MARK_COUPON_RELATE_USER.COUPON_ID IS '优惠券活动ID';
COMMENT ON COLUMN LVMAMA_PET.MARK_COUPON_RELATE_USER.CREATE_TIME IS '创建时间';

update LVMAMA_PET.MARK_COUPON_RELATE_USER  u set u.COUPON_ID =
select code.coupon_id from LVMAMA_PET.MARK_COUPON_CODE code where code.coupon_code_id = u.coupon_code_id




ALTER TABLE LVMAMA_PET.MARK_COUPON_RELATE_USER ADD RED_ENVELOPE  NUMBER(11) DEFAULT  0;
COMMENT ON COLUMN LVMAMA_PET.MARK_COUPON_RELATE_USER.RED_ENVELOPE IS '是否红包  1  是   0 否';


ALTER TABLE LVMAMA_PET.MARK_COUPON_RELATE_USER ADD COUPON_CODE_CREATE_TIME DATE ;
ALTER TABLE LVMAMA_PET.MARK_COUPON_RELATE_USER ADD COUPON_CODE_USED VARCHAR2(10) ;
COMMENT ON COLUMN LVMAMA_PET.MARK_COUPON_RELATE_USER.COUPON_CODE_CREATE_TIME IS '券码创建时间';
COMMENT ON COLUMN LVMAMA_PET.MARK_COUPON_RELATE_USER.COUPON_CODE_USED IS '券码是否已经使用(true/false)';




